package io.stacs.nav.drs.service;

import com.alibaba.fastjson.JSON;
import io.stacs.nav.drs.api.model.TransactionPO;
import io.stacs.nav.drs.api.model.bo.Block;
import io.stacs.nav.drs.service.dao.po.BlockPO;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;

import java.util.List;
import java.util.stream.Collectors;

import static io.stacs.nav.drs.service.model.ConvertHelper.blockHeader2BlockPO;
import static io.stacs.nav.drs.service.model.ConvertHelper.signedTx2TxPO;
import static io.stacs.nav.drs.service.model.JsonFieldTypeResolvers.dateFieldResolver;

/**
 * @author dekuofa <br>
 * @date 2019-12-09 <br>
 */
// @Slf4j @RunWith(ArkBootRunner.class) @SpringBootTest(classes = ConfigWithoutDataSource.class)
@Slf4j public class BlockCallbackProcessTest {
    String message = "{\n" + "      \"blockHeader\": {\n"
        + "        \"blockHash\": \"0b586f8f45b65115595e55c81a50983cd5087a3beb42dcb13cf6448bdf07ea69\",\n"
        + "        \"blockTime\": 1561939200000,\n" + "        \"height\": 1,\n"
        + "        \"previousHash\": \"D40114568F302846D8CFEDD04C87F30ABC9DBFE568F89E44F97FD581BA97BBC4\",\n"
        + "        \"stateRootHash\": {\n" + "          \"accountRootHash\": \"STACS_NO_TREE\",\n"
        + "          \"caRootHash\": \"2716364f7fb9484d8af035248443fef09a4edfec54605de64441a12aa9654c25\",\n"
        + "          \"contractRootHash\": \"STACS_NO_TREE\",\n"
        + "          \"policyRootHash\": \"6e844a64fd8f656bc6749f3213fa4939ad8072a51c08d3aae9718efccd7d104a\",\n"
        + "          \"rsRootHash\": \"57ecda40ae129ce91189d1a2855c67917b0629fbac82b9bef1d7b0d41a51caed\",\n"
        + "          \"txReceiptRootHash\": \"STACS_NO_TREE\",\n"
        + "          \"txRootHash\": \"1457dea63d47dd244693266d9270443423a2dd17fa924e4822d4b289bf154d9a\"\n"
        + "        },\n" + "        \"totalTxNum\": 5,\n" + "        \"version\": \"v1.0\"\n" + "      },\n"
        + "      \"genesis\": true,\n" + "      \"signedTxList\": [\n" + "        {\n" + "          \"coreTx\": {\n"
        + "            \"actionList\": [\n" + "              {\n" + "                \"index\": 0,\n"
        + "                \"permissionName\": \"DEFAULT\",\n" + "                \"type\": \"PERMISSION_REGISTER\",\n"
        + "                \"version\": \"1.0.0\"\n" + "              },\n" + "              {\n"
        + "                \"index\": 1,\n" + "                \"permissionName\": \"RS\",\n"
        + "                \"type\": \"PERMISSION_REGISTER\",\n" + "                \"version\": \"1.0.0\"\n"
        + "              }\n" + "            ],\n" + "            \"bizModel\": {\n"
        + "              \"Copyright\": \"STACS © 2019. All Rights Reserved\",\n"
        + "              \"GeniusData\": \"535441435320c2a920323031392e20416c6c20526967687473205265736572766564\"\n"
        + "            },\n" + "            \"dealCount\": 1,\n" + "            \"policyId\": \"IS_NULL\",\n"
        + "            \"policyVersion\": 0,\n" + "            \"sendTime\": 1561939200000,\n"
        + "            \"sender\": \"StacsGeniusBlock\",\n"
        + "            \"txId\": \"4ccc3753b6ee34a2a48a6d85526acdff60ef94e58fef12a55c47eaa9d932e9a5\",\n"
        + "            \"txType\": \"DEFAULT\",\n" + "            \"version\": \"2.0.0\"\n" + "          },\n"
        + "          \"receipt\": {\n" + "            \"result\": false,\n"
        + "            \"txId\": \"4ccc3753b6ee34a2a48a6d85526acdff60ef94e58fef12a55c47eaa9d932e9a5\",\n"
        + "            \"version\": \"2.0.0\"\n" + "          }\n" + "        },\n" + "        {\n"
        + "          \"coreTx\": {\n" + "            \"actionList\": [\n" + "              {\n"
        + "                \"callbackType\": \"ALL\",\n" + "                \"decisionType\": \"FULL_VOTE\",\n"
        + "                \"domainIds\": [\"Domain\"],\n" + "                \"index\": 0,\n"
        + "                \"policyId\": \"AUTHORIZE_PERMISSION\",\n"
        + "                \"policyName\": \"AUTHORIZE_PERMISSION\",\n"
        + "                \"type\": \"REGISTER_POLICY\",\n" + "                \"verifyNum\": 0,\n"
        + "                \"version\": \"1.0.0\",\n" + "                \"votePattern\": \"ASYNC\"\n"
        + "              },\n" + "              {\n" + "                \"callbackType\": \"ALL\",\n"
        + "                \"decisionType\": \"FULL_VOTE\",\n" + "                \"domainIds\": [\"Domain\"],\n"
        + "                \"index\": 1,\n" + "                \"policyId\": \"BD_PUBLISH\",\n"
        + "                \"policyName\": \"BD_PUBLISH\",\n" + "                \"type\": \"REGISTER_POLICY\",\n"
        + "                \"verifyNum\": 0,\n" + "                \"version\": \"1.0.0\",\n"
        + "                \"votePattern\": \"ASYNC\"\n" + "              },\n" + "              {\n"
        + "                \"callbackType\": \"ALL\",\n" + "                \"decisionType\": \"FULL_VOTE\",\n"
        + "                \"domainIds\": [\"Domain\"],\n" + "                \"index\": 2,\n"
        + "                \"policyId\": \"BUILD_SNAPSHOT\",\n"
        + "                \"policyName\": \"BUILD_SNAPSHOT\",\n" + "                \"type\": \"REGISTER_POLICY\",\n"
        + "                \"verifyNum\": 0,\n" + "                \"version\": \"1.0.0\",\n"
        + "                \"votePattern\": \"ASYNC\"\n" + "              },\n" + "              {\n"
        + "                \"callbackType\": \"ALL\",\n" + "                \"decisionType\": \"FULL_VOTE\",\n"
        + "                \"domainIds\": [\"Domain\"],\n" + "                \"index\": 3,\n"
        + "                \"policyId\": \"CANCEL_PERMISSION\",\n"
        + "                \"policyName\": \"CANCEL_PERMISSION\",\n"
        + "                \"type\": \"REGISTER_POLICY\",\n" + "                \"verifyNum\": 0,\n"
        + "                \"version\": \"1.0.0\",\n" + "                \"votePattern\": \"ASYNC\"\n"
        + "              },\n" + "              {\n" + "                \"callbackType\": \"ALL\",\n"
        + "                \"decisionType\": \"FULL_VOTE\",\n" + "                \"domainIds\": [\"Domain\"],\n"
        + "                \"index\": 4,\n" + "                \"policyId\": \"IDENTITY_BD_MANAGE\",\n"
        + "                \"policyName\": \"IDENTITY_BD_MANAGE\",\n"
        + "                \"type\": \"REGISTER_POLICY\",\n" + "                \"verifyNum\": 0,\n"
        + "                \"version\": \"1.0.0\",\n" + "                \"votePattern\": \"ASYNC\"\n"
        + "              },\n" + "              {\n" + "                \"callbackType\": \"ALL\",\n"
        + "                \"decisionType\": \"FULL_VOTE\",\n" + "                \"domainIds\": [\"Domain\"],\n"
        + "                \"index\": 5,\n" + "                \"policyId\": \"IDENTITY_SETTING\",\n"
        + "                \"policyName\": \"IDENTITY_SETTING\",\n" + "                \"type\": \"REGISTER_POLICY\",\n"
        + "                \"verifyNum\": 0,\n" + "                \"version\": \"1.0.0\",\n"
        + "                \"votePattern\": \"ASYNC\"\n" + "              },\n" + "              {\n"
        + "                \"callbackType\": \"ALL\",\n" + "                \"decisionType\": \"FULL_VOTE\",\n"
        + "                \"domainIds\": [\"Domain\"],\n" + "                \"index\": 6,\n"
        + "                \"policyId\": \"KYC_SETTING\",\n" + "                \"policyName\": \"KYC_SETTING\",\n"
        + "                \"type\": \"REGISTER_POLICY\",\n" + "                \"verifyNum\": 0,\n"
        + "                \"version\": \"1.0.0\",\n" + "                \"votePattern\": \"ASYNC\"\n"
        + "              },\n" + "              {\n" + "                \"callbackType\": \"ALL\",\n"
        + "                \"decisionType\": \"FULL_VOTE\",\n" + "                \"domainIds\": [\"Domain\"],\n"
        + "                \"index\": 7,\n" + "                \"policyId\": \"PERMISSION_REGISTER\",\n"
        + "                \"policyName\": \"PERMISSION_REGISTER\",\n"
        + "                \"type\": \"REGISTER_POLICY\",\n" + "                \"verifyNum\": 0,\n"
        + "                \"version\": \"1.0.0\",\n" + "                \"votePattern\": \"ASYNC\"\n"
        + "              },\n" + "              {\n" + "                \"callbackType\": \"ALL\",\n"
        + "                \"decisionType\": \"FULL_VOTE\",\n" + "                \"domainIds\": [\"Domain\"],\n"
        + "                \"index\": 8,\n" + "                \"policyId\": \"SAVE_ATTESTATION\",\n"
        + "                \"policyName\": \"SAVE_ATTESTATION\",\n" + "                \"type\": \"REGISTER_POLICY\",\n"
        + "                \"verifyNum\": 0,\n" + "                \"version\": \"1.0.0\",\n"
        + "                \"votePattern\": \"ASYNC\"\n" + "              },\n" + "              {\n"
        + "                \"callbackType\": \"ALL\",\n" + "                \"decisionType\": \"FULL_VOTE\",\n"
        + "                \"domainIds\": [\"Domain\"],\n" + "                \"index\": 9,\n"
        + "                \"policyId\": \"SET_FEE_RULE\",\n" + "                \"policyName\": \"SET_FEE_RULE\",\n"
        + "                \"type\": \"REGISTER_POLICY\",\n" + "                \"verifyNum\": 0,\n"
        + "                \"version\": \"1.0.0\",\n" + "                \"votePattern\": \"ASYNC\"\n"
        + "              },\n" + "              {\n" + "                \"callbackType\": \"ALL\",\n"
        + "                \"decisionType\": \"FULL_VOTE\",\n" + "                \"domainIds\": [\"Domain\"],\n"
        + "                \"index\": 10,\n" + "                \"policyId\": \"SYSTEM_PROPERTY\",\n"
        + "                \"policyName\": \"SYSTEM_PROPERTY\",\n" + "                \"type\": \"REGISTER_POLICY\",\n"
        + "                \"verifyNum\": 0,\n" + "                \"version\": \"1.0.0\",\n"
        + "                \"votePattern\": \"ASYNC\"\n" + "              }\n" + "            ],\n"
        + "            \"bizModel\": {\n" + "              \"Copyright\": \"STACS © 2019. All Rights Reserved\",\n"
        + "              \"GeniusData\": \"535441435320c2a920323031392e20416c6c20526967687473205265736572766564\"\n"
        + "            },\n" + "            \"dealCount\": 1,\n" + "            \"policyId\": \"IS_NULL\",\n"
        + "            \"policyVersion\": 0,\n" + "            \"sendTime\": 1561939200000,\n"
        + "            \"sender\": \"StacsGeniusBlock\",\n"
        + "            \"txId\": \"6e844a64fd8f656bc6749f3213fa4939ad8072a51c08d3aae9718efccd7d104a\",\n"
        + "            \"txType\": \"DEFAULT\",\n" + "            \"version\": \"2.0.0\"\n" + "          },\n"
        + "          \"receipt\": {\n" + "            \"result\": false,\n"
        + "            \"txId\": \"6e844a64fd8f656bc6749f3213fa4939ad8072a51c08d3aae9718efccd7d104a\",\n"
        + "            \"version\": \"2.0.0\"\n" + "          }\n" + "        },\n" + "        {\n"
        + "          \"coreTx\": {\n" + "            \"actionList\": [\n" + "              {\n"
        + "                \"bdType\": \"system\",\n" + "                \"bdVersion\": \"1.0\",\n"
        + "                \"code\": \"SystemBD\",\n" + "                \"functions\": [\n" + "                  {\n"
        + "                    \"desc\": \"Identity设置\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"IDENTITY_SETTING\",\n"
        + "                    \"methodSign\": \"IDENTITY_SETTING\",\n"
        + "                    \"name\": \"IDENTITY_SETTING\",\n"
        + "                    \"signValue\": \"IDENTITY_SETTINGSystemActionIdentity设置IDENTITY_SETTINGDEFAULTIDENTITY_SETTING\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"BD发布\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"BD_PUBLISH\",\n"
        + "                    \"methodSign\": \"BD_PUBLISH\",\n" + "                    \"name\": \"BD_PUBLISH\",\n"
        + "                    \"signValue\": \"BD_PUBLISHSystemActionBD发布BD_PUBLISHDEFAULTBD_PUBLISH\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"Permission注册\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"PERMISSION_REGISTER\",\n"
        + "                    \"methodSign\": \"PERMISSION_REGISTER\",\n"
        + "                    \"name\": \"PERMISSION_REGISTER\",\n"
        + "                    \"signValue\": \"PERMISSION_REGISTERSystemActionPermission注册PERMISSION_REGISTERDEFAULTPERMISSION_REGISTER\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"Permission授权\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"AUTHORIZE_PERMISSION\",\n"
        + "                    \"methodSign\": \"AUTHORIZE_PERMISSION\",\n"
        + "                    \"name\": \"AUTHORIZE_PERMISSION\",\n"
        + "                    \"signValue\": \"AUTHORIZE_PERMISSIONSystemActionPermission授权AUTHORIZE_PERMISSIONDEFAULTAUTHORIZE_PERMISSION\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"Permission撤销授权\",\n"
        + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"CANCEL_PERMISSION\",\n"
        + "                    \"methodSign\": \"CANCEL_PERMISSION\",\n"
        + "                    \"name\": \"CANCEL_PERMISSION\",\n"
        + "                    \"signValue\": \"CANCEL_PERMISSIONSystemActionPermission撤销授权CANCEL_PERMISSIONDEFAULTCANCEL_PERMISSION\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"Policy注册\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"REGISTER_POLICY\",\n"
        + "                    \"methodSign\": \"REGISTER_POLICY\",\n"
        + "                    \"name\": \"REGISTER_POLICY\",\n"
        + "                    \"signValue\": \"REGISTER_POLICYSystemActionPolicy注册REGISTER_POLICYDEFAULTREGISTER_POLICY\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"Policy修改\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"MODIFY_POLICY\",\n"
        + "                    \"methodSign\": \"MODIFY_POLICY\",\n"
        + "                    \"name\": \"MODIFY_POLICY\",\n"
        + "                    \"signValue\": \"MODIFY_POLICYSystemActionPolicy修改MODIFY_POLICYDEFAULTMODIFY_POLICY\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"RS注册\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"REGISTER_RS\",\n"
        + "                    \"methodSign\": \"REGISTER_RS\",\n" + "                    \"name\": \"REGISTER_RS\",\n"
        + "                    \"signValue\": \"REGISTER_RSSystemActionRS注册REGISTER_RSDEFAULTREGISTER_RS\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"RS撤销\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"CANCEL_RS\",\n"
        + "                    \"methodSign\": \"CANCEL_RS\",\n" + "                    \"name\": \"CANCEL_RS\",\n"
        + "                    \"signValue\": \"CANCEL_RSSystemActionRS撤销CANCEL_RSDEFAULTCANCEL_RS\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"CA认证\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"CA_AUTH\",\n" + "                    \"methodSign\": \"CA_AUTH\",\n"
        + "                    \"name\": \"CA_AUTH\",\n"
        + "                    \"signValue\": \"CA_AUTHSystemActionCA认证CA_AUTHDEFAULTCA_AUTH\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"CA撤销\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"CA_CANCEL\",\n"
        + "                    \"methodSign\": \"CA_CANCEL\",\n" + "                    \"name\": \"CA_CANCEL\",\n"
        + "                    \"signValue\": \"CA_CANCELSystemActionCA撤销CA_CANCELDEFAULTCA_CANCEL\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"CA更新\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"CA_UPDATE\",\n"
        + "                    \"methodSign\": \"CA_UPDATE\",\n" + "                    \"name\": \"CA_UPDATE\",\n"
        + "                    \"signValue\": \"CA_UPDATESystemActionCA更新CA_UPDATEDEFAULTCA_UPDATE\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"节点加入\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"NODE_JOIN\",\n"
        + "                    \"methodSign\": \"NODE_JOIN\",\n" + "                    \"name\": \"NODE_JOIN\",\n"
        + "                    \"signValue\": \"NODE_JOINSystemAction节点加入NODE_JOINDEFAULTNODE_JOIN\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"节点退出\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"NODE_LEAVE\",\n"
        + "                    \"methodSign\": \"NODE_LEAVE\",\n" + "                    \"name\": \"NODE_LEAVE\",\n"
        + "                    \"signValue\": \"NODE_LEAVESystemAction节点退出NODE_LEAVEDEFAULTNODE_LEAVE\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"系统属性配置\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"SYSTEM_PROPERTY\",\n"
        + "                    \"methodSign\": \"SYSTEM_PROPERTY\",\n"
        + "                    \"name\": \"SYSTEM_PROPERTY\",\n"
        + "                    \"signValue\": \"SYSTEM_PROPERTYSystemAction系统属性配置SYSTEM_PROPERTYDEFAULTSYSTEM_PROPERTY\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"Identity BD 管理（froze/unfroze）\",\n"
        + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"IDENTITY_BD_MANAGE\",\n"
        + "                    \"methodSign\": \"IDENTITY_BD_MANAGE\",\n"
        + "                    \"name\": \"IDENTITY_BD_MANAGE\",\n"
        + "                    \"signValue\": \"IDENTITY_BD_MANAGESystemActionIdentity BD 管理（froze/unfroze）IDENTITY_BD_MANAGEDEFAULTIDENTITY_BD_MANAGE\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"identity kyc 设置\",\n"
        + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"KYC_SETTING\",\n"
        + "                    \"methodSign\": \"KYC_SETTING\",\n" + "                    \"name\": \"KYC_SETTING\",\n"
        + "                    \"signValue\": \"KYC_SETTINGSystemActionidentity kyc 设置KYC_SETTINGDEFAULTKYC_SETTING\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"手续费设置：合约地址 \\u0026 收取地址\",\n"
        + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"SET_FEE_CONFIG\",\n"
        + "                    \"methodSign\": \"SET_FEE_CONFIG\",\n"
        + "                    \"name\": \"SET_FEE_CONFIG\",\n"
        + "                    \"signValue\": \"SET_FEE_CONFIGSystemAction手续费设置：合约地址 \\u0026 收取地址SET_FEE_CONFIGDEFAULTSET_FEE_CONFIG\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"手续费费率配置\",\n" + "                    \"execPermission\": \"RS\",\n"
        + "                    \"execPolicy\": \"SET_FEE_RULE\",\n"
        + "                    \"methodSign\": \"SET_FEE_RULE\",\n"
        + "                    \"name\": \"SET_FEE_RULE\",\n"
        + "                    \"signValue\": \"SET_FEE_RULESystemAction手续费费率配置SET_FEE_RULERSSET_FEE_RULE\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"保存存证\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"SAVE_ATTESTATION\",\n"
        + "                    \"methodSign\": \"SAVE_ATTESTATION\",\n"
        + "                    \"name\": \"SAVE_ATTESTATION\",\n"
        + "                    \"signValue\": \"SAVE_ATTESTATIONSystemAction保存存证SAVE_ATTESTATIONDEFAULTSAVE_ATTESTATION\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  },\n" + "                  {\n"
        + "                    \"desc\": \"打快照\",\n" + "                    \"execPermission\": \"DEFAULT\",\n"
        + "                    \"execPolicy\": \"BUILD_SNAPSHOT\",\n"
        + "                    \"methodSign\": \"BUILD_SNAPSHOT\",\n"
        + "                    \"name\": \"BUILD_SNAPSHOT\",\n"
        + "                    \"signValue\": \"BUILD_SNAPSHOTSystemAction打快照BUILD_SNAPSHOTDEFAULTBUILD_SNAPSHOT\",\n"
        + "                    \"type\": \"SystemAction\"\n" + "                  }\n" + "                ],\n"
        + "                \"index\": 0,\n" + "                \"name\": \"SystemBD\",\n"
        + "                \"type\": \"BD_PUBLISH\",\n" + "                \"version\": \"1.0.0\"\n"
        + "              }\n" + "            ],\n" + "            \"bizModel\": {\n"
        + "              \"Copyright\": \"STACS © 2019. All Rights Reserved\",\n"
        + "              \"GeniusData\": \"535441435320c2a920323031392e20416c6c20526967687473205265736572766564\"\n"
        + "            },\n" + "            \"dealCount\": 1,\n" + "            \"policyId\": \"IS_NULL\",\n"
        + "            \"policyVersion\": 0,\n" + "            \"sendTime\": 1561939200000,\n"
        + "            \"sender\": \"StacsGeniusBlock\",\n"
        + "            \"txId\": \"4707c5e268bca6bcd66b36b85f34cb7e97ef1c1d60a5730f8174a8fef3935486\",\n"
        + "            \"txType\": \"DEFAULT\",\n" + "            \"version\": \"2.0.0\"\n" + "          },\n"
        + "          \"receipt\": {\n" + "            \"result\": false,\n"
        + "            \"txId\": \"4707c5e268bca6bcd66b36b85f34cb7e97ef1c1d60a5730f8174a8fef3935486\",\n"
        + "            \"version\": \"2.0.0\"\n" + "          }\n" + "        },\n" + "        {\n"
        + "          \"coreTx\": {\n" + "            \"actionList\": [\n" + "              {\n"
        + "                \"domainId\": \"Domain\",\n"
        + "                \"pubKey\": \"04ba98bf34af47145cf552b710570538b37bf3eff124e51c3361d02ea128c0447737be86077667feaca6dbc0679ae0653c4887d328a2b9d6d7f777599c287bf054\",\n"
        + "                \"type\": \"CA_INIT\",\n" + "                \"usage\": \"biz\",\n"
        + "                \"user\": \"STACS-TEST0\",\n" + "                \"valid\": false,\n"
        + "                \"version\": \"1.0.0\"\n" + "              },\n" + "              {\n"
        + "                \"domainId\": \"Domain\",\n"
        + "                \"pubKey\": \"04eb1a1d24b2456b600b5ba594f9783a6d51bec678ef57cdb5c7127d107a956c0240e89d41bfe164e8ef7a21f43f4c16e6a46874d9835929422b3264602186c79c\",\n"
        + "                \"type\": \"CA_INIT\",\n" + "                \"usage\": \"consensus\",\n"
        + "                \"user\": \"STACS-TEST0\",\n" + "                \"valid\": false,\n"
        + "                \"version\": \"1.0.0\"\n" + "              }\n" + "            ],\n"
        + "            \"bizModel\": {\n" + "              \"Copyright\": \"STACS © 2019. All Rights Reserved\",\n"
        + "              \"GeniusData\": \"535441435320c2a920323031392e20416c6c20526967687473205265736572766564\"\n"
        + "            },\n" + "            \"dealCount\": 1,\n" + "            \"policyId\": \"IS_NULL\",\n"
        + "            \"policyVersion\": 0,\n" + "            \"sendTime\": 1561939200000,\n"
        + "            \"sender\": \"StacsGeniusBlock\",\n"
        + "            \"txId\": \"2716364f7fb9484d8af035248443fef09a4edfec54605de64441a12aa9654c25\",\n"
        + "            \"txType\": \"DEFAULT\",\n" + "            \"version\": \"2.0.0\"\n" + "          },\n"
        + "          \"receipt\": {\n" + "            \"result\": false,\n"
        + "            \"txId\": \"2716364f7fb9484d8af035248443fef09a4edfec54605de64441a12aa9654c25\",\n"
        + "            \"version\": \"2.0.0\"\n" + "          }\n" + "        },\n" + "        {\n"
        + "          \"coreTx\": {\n" + "            \"actionList\": [\n" + "              {\n"
        + "                \"desc\": \"by stacs init\",\n" + "                \"domainId\": \"Domain\",\n"
        + "                \"index\": 0,\n" + "                \"maxNodeSize\": 1,\n"
        + "                \"rsId\": \"STACS-TEST0\",\n" + "                \"type\": \"REGISTER_RS\",\n"
        + "                \"version\": \"1.0.0\"\n" + "              }\n" + "            ],\n"
        + "            \"bizModel\": {\n" + "              \"Copyright\": \"STACS © 2019. All Rights Reserved\",\n"
        + "              \"GeniusData\": \"535441435320c2a920323031392e20416c6c20526967687473205265736572766564\"\n"
        + "            },\n" + "            \"dealCount\": 1,\n" + "            \"policyId\": \"IS_NULL\",\n"
        + "            \"policyVersion\": 0,\n" + "            \"sendTime\": 1561939200000,\n"
        + "            \"sender\": \"StacsGeniusBlock\",\n"
        + "            \"txId\": \"57ecda40ae129ce91189d1a2855c67917b0629fbac82b9bef1d7b0d41a51caed\",\n"
        + "            \"txType\": \"DEFAULT\",\n" + "            \"version\": \"2.0.0\"\n" + "          },\n"
        + "          \"receipt\": {\n" + "            \"result\": false,\n"
        + "            \"txId\": \"57ecda40ae129ce91189d1a2855c67917b0629fbac82b9bef1d7b0d41a51caed\",\n"
        + "            \"version\": \"2.0.0\"\n" + "          }\n" + "        }\n" + "      ]\n" + "    }";

    @Test public void test() {
        Block block = JSON.parseObject(message, Block.class, dateFieldResolver);
        BlockPO blockPO = blockHeader2BlockPO.apply(block.getBlockHeader());
        List<TransactionPO> txList = block.getSignedTxList().stream().map(signedTx2TxPO).collect(Collectors.toList());
        log.info(blockPO.toString());
    }
}
